import Head from "next/head";

import ImageFeed from "../components/ImageFeed"; // Import your ImageFeed component

export default function Home() {
  const names = [
    "can",
    "tableware",
    "late",
    "tickets",
    "meat",
    "oldcar",
    "oldcar2",
    "vacation",
    "",
    "0",
    "balloons",
    "bread",
    "breakd",
    "cake",
    "cheese",
    "coffee",
    "doughnut",
    "egg",
    "icecream",
    "office",
    "pakchoy",
    "pills",
    "pizza",
    "plant",
    "puppy",
    "weather",
  ];

  const NameBoxes: React.FC = () => {
    return (
      <div className="flex flex-row flex-wrap items-center gap-2 p-4">
        {names.map((name, index) => (
          <div
            key={index}
            className="inline-block border border-white px-2 text-sm font-light"
          >
            {name}
          </div>
        ))}
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Riff</title>
        <meta name="description" content="Riff Image Feed" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-black font-sans text-white">
        <header className="p-4">
          <div className="text-2xl font-normal">
            MIDJOURNEY GENERATED, HIGHLY AESTHETIC, CURATED, FREE, PNG ASSETS,
            AND PROMPTS
          </div>
          <div className="font-light">
            All images are generated by mid-journey through a paid subscription
            plan, and can be used freely. Read{" "}
            <a
              href="https://docs.midjourney.com/docs/terms-of-service"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
            >
              here
            </a>{" "}
            for more information about license.
            <br />
            Images were post-processed with background removal, object
            detection, and cropping. <br />
            More images ? Feel free to{" "}
            <a
              href="https://twitter.com/hmpark89462737"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
            >
              tweet
            </a>
            , or contact me. Made by{" "}
            <a
              href="https://hongminpark.univer.se/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
            >
              hmpark
            </a>
          </div>
        </header>
        <main className="flex flex-col gap-4">
          <NameBoxes />
          <ImageFeed />
          <div className="text-s flex flex-col items-center justify-center gap-4 p-16 text-center font-light">
            Support me with upvote if you liked!
            <a
              href="https://www.producthunt.com/posts/midjourney-png-assets-curation?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-midjourney&#0045;png&#0045;assets&#0045;curation"
              target="_blank"
            >
              <img
                src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=405777&theme=light"
                alt="MidJourney&#0032;PNG&#0032;Assets&#0032;Curation - Curation&#0032;of&#0032;200&#0043;&#0032;MJ&#0032;generated&#0032;aesthetic&#0032;free&#0032;pngs&#0044;&#0032;prompts | Product Hunt"
                style={{ width: "250px", height: "54px" }}
                width="250"
                height="54"
              />
            </a>{" "}
          </div>
        </main>
      </div>
    </>
  );
}
